package game.engine.dataloader;
import java.io.*;
import game.engine.titans.*;
import game.engine.weapons.*;
import java.util.*;
import game.engine.weapons.factory.*;
public class DataLoader {
	
	final static private String TITANS_FILE_NAME = "titans.csv" ;
	final static private String WEAPONS_FILE_NAME = "weapons.csv" ;
	 
	// we added a constructor
	//public DataLoader(String TITANS_FILE_NAME,String WEAPONS_FILE_NAME ){
		//this.TITANS_FILE_NAME = TITANS_FILE_NAME;
		//this.WEAPONS_FILE_NAME = WEAPONS_FILE_NAME;
	//}
	
	public String getTITANS_FILE_NAME() {
		return TITANS_FILE_NAME;
	}
	public String getWEAPONS_FILE_NAME() {
		return WEAPONS_FILE_NAME;
	}
	public static HashMap<Integer, TitanRegistry> readTitanRegistry() throws IOException {
        String titansFileName = "titans.csv";
        HashMap<Integer, TitanRegistry> titanRegistry = new HashMap<>();
        try (BufferedReader br = new BufferedReader(new FileReader(titansFileName))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");
                int code = Integer.parseInt(values[0]);
                int baseHealth = Integer.parseInt(values[1]);
                int baseDamage = Integer.parseInt(values[2]);
                int heightInMeters = Integer.parseInt(values[3]);
                int speed = Integer.parseInt(values[4]);
                int resourcesValue = Integer.parseInt(values[5]);
                int dangerLevel = Integer.parseInt(values[6]);
                TitanRegistry titan = new TitanRegistry(code, baseHealth, baseDamage, heightInMeters, speed, resourcesValue, dangerLevel);
                titanRegistry.put(code, titan);
            }
        }
        return titanRegistry;
    } // this method is generated by the help of AI
	

    public static HashMap<Integer, WeaponRegistry> readWeaponRegistry() throws IOException {
        String weaponsFileName = "weapons.csv";
        HashMap<Integer, WeaponRegistry> weaponRegistry = new HashMap<>();
        try (BufferedReader br = new BufferedReader(new FileReader(weaponsFileName))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");
                int code = Integer.parseInt(values[0]);
                int price = Integer.parseInt(values[1]);
                int damage = Integer.parseInt(values[2]);
                String name = values[3];
                int minRange = 0;
                int maxRange = 0;
                if (values.length > 4) {
                    minRange = Integer.parseInt(values[4]);
                    maxRange = Integer.parseInt(values[5]);
                }
                WeaponRegistry weapon = new WeaponRegistry(code, price, damage, name, minRange, maxRange);
                weaponRegistry.put(code, weapon);
            }
        }
        return weaponRegistry;
    } // this method is generated by the help of AI
	
}
